# Generated by Django 3.1.1 on 2020-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('detials', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
