# Generated by Django 3.1.1 on 2020-09-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginfo',
            old_name='detials',
            new_name='details',
        ),
    ]
