# Generated by Django 3.1.1 on 2020-09-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200904_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='date',
            field=models.DateField(),
        ),
    ]
